export const ADMIN_ROLLS_REQUEST = 'ADMIN_ROLLS_REQUEST'
export const ADMIN_ROLLS_SUCCESS = 'ADMIN_ROLLS_SUCCESS'
export const ADMIN_ROLLS_FAIL = 'ADMIN_ROLLS_FAIL'

export const ALL_ROLLS_REQUEST = 'ALL_ROLLS_REQUEST'
export const ALL_ROLLS_SUCCESS = 'ALL_ROLLS_SUCCESS'
export const ALL_ROLLS_FAIL = 'ALL_ROLLS_FAIL'

export const NEW_ROLL_REQUEST = 'NEW_ROLL_REQUEST'
export const NEW_ROLL_SUCCESS = 'NEW_ROLL_SUCCESS'
export const NEW_ROLL_RESET = 'NEW_ROLL_RESET'
export const NEW_ROLL_FAIL = 'NEW_ROLL_FAIL'

export const DELETE_ROLL_REQUEST = 'DELETE_ROLL_REQUEST'
export const DELETE_ROLL_SUCCESS = 'DELETE_ROLL_SUCCESS'
export const DELETE_ROLL_RESET = 'DELETE_ROLL_RESET'
export const DELETE_ROLL_FAIL = 'DELETE_ROLL_FAIL'

export const UPDATE_ROLL_REQUEST = 'UPDATE_ROLL_REQUEST'
export const UPDATE_ROLL_SUCCESS = 'UPDATE_ROLL_SUCCESS'
export const UPDATE_ROLL_RESET = 'UPDATE_ROLL_RESET'
export const UPDATE_ROLL_FAIL = 'UPDATE_ROLL_FAIL'

export const ROLL_DETAILS_REQUEST = 'ROLL_DETAILS_REQUEST'
export const ROLL_DETAILS_SUCCESS = 'ROLL_DETAILS_SUCCESS'
export const ROLL_DETAILS_FAIL = 'ROLL_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'